# Generated by Django 3.2 on 2021-04-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
